### ISSUE TITLE
F-Droid release

### ISSUE THREAD

**Issue by IzzySoft** [cyb3rko/pazzword#1]
Thanks for making your app available under a free license! Would you also consider making the APK available, ideally attached to your [releases](https://github.com/cyb3rko/pazzword/releases) here – so folks without Play Store access can use it as well? Thanks in advance!

**Comment by cyb3rko** [comment]
It's the real Izzy :open_mouth: . Servus!
Thanks for your message.

As I recently published my first app which became "quite popular" ([FlashDim](https://github.com/cyb3rko/flashdim), a few thousand downloads, but for me it's still a lot) I decided to upload it to F-Droid.
I think I will do the same with my other apps which currently aren't.

One question: I'm always interested in how you discovered this app. Via GitHub recommendations?

**Comment by IzzySoft** [comment]
> It's the real Izzy :open_mouth: . Servus!

The very one – and "Apaches"… urn, sorry. No idea if that movie was even available in English… Oh: [it is](https://en.wikipedia.org/wiki/Der_Schuh_des_Manitu) :see_no_evil:

> I decided to upload it to F-Droid.

Hihi… "One does not simply upload an app to F-Droid", but I guess I know what you mean, so: fantastico! In this case, feel free to rename this issue to "F-Droid release" or something along those lines to track progress.

> I'm always interested in how you discovered this app. Via GitHub recommendations?

Kind of: My very own crawler :smile: 
![image](https://user-images.githubusercontent.com/6781438/206282282-7443c841-8208-4bdf-848d-28246cabab57.png)

All kind of filters applied so I only need to check around 5..10 percent, which is bearable. I run that almost every day, but still some apps slip through my net…

**Comment by cyb3rko** [comment]
> One does not simply upload an app to F-Droid

Yeah, you know what I mean.



> Kind of: My very own crawler 😄

Oh, interesting.

**Comment by cyb3rko** [comment]
Done

**Comment by IzzySoft** [comment]
Congrats! :star_struck:
