### ISSUE TITLE
Password generator output length resetting on tab switch

### ISSUE THREAD

**Issue by miranyx** [cyb3rko/pazzword#2]
The length in the password gen is the same as the one entered in the input field for the password. Even if you changed it beforehand.

**Comment by cyb3rko** [comment]
What exactly do you mean? Could you explain how I can recreate this?

For me it seems to work.

**Comment by miranyx** [comment]
Ah, okay the steps to reproduce are:

1. Generate a password: "Alphanumeric + Symbols", the length can be any.
2. Copy it.
3. Change the slider for the length.
4. Paste the copied password into the analyze input.
5. Press the analyze button.
6. Go back to the generator.

The length will say 12. Not the length specified earlier, the slider will still be at the same position as positionef earlier.

**Comment by cyb3rko** [comment]
I understand now.

Actually, you don't have to copy anything. Just change the length, switch to another tab and come back to the generator.
Thank you for reporting.

**Comment by jensMF** [comment]
Interestingly it creates passwords with the previuos selected length not with a length of 12.
Same result for passphrase btw.

**Comment by cyb3rko** [comment]
@benni347 @jensMF Should be fixed in [Version 1.2.3](https://github.com/cyb3rko/pazzword/releases/tag/v1.2.3), can you confirm?

**Comment by miranyx** [comment]
Can't reproduce it in Version 1.2.3.
